#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft3d47.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft3d47.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft8716.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft8716.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft8607.o	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft8607.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft5x46.o	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft5x46.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft6x36.o	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft6x36.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft5822.o	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft5822.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft8006.o	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft8006.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft8736.o	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft8736.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_fte716.o	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_fte716.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft8606.o	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft8606.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft3c47.o	
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft3c47.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_supported_ic.o
